Traceback (most recent call last):
  File "main.py", line 25, in <module>
    import numpy as np
  File "/mnt/cephfs/mixed/home/luohailin/envs/torch10/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/mnt/cephfs/mixed/home/luohailin/envs/torch10/lib/python3.8/site-packages/numpy/core/__init__.py", line 73, in <module>
    from . import numeric
  File "/mnt/cephfs/mixed/home/luohailin/envs/torch10/lib/python3.8/site-packages/numpy/core/numeric.py", line 30, in <module>
    from ._ufunc_config import errstate
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 934, in get_code
  File "<frozen importlib._bootstrap_external>", line 1033, in get_data
KeyboardInterrupt
